#' Access Singstat Resource ID Endpoint
#'
#' @description Constructs a request to the SingStat Table Builder Resource ID Endpoint and sends a GET request.
#' Returns a dataframe of the SingStat tables and their corresponding resource IDs that match the search.
#'
#' @param keyword Compulsory argument. The search query.
#' @param searchOption Where one wants to search for the keyword. See details.
#' @param printSummary Defaults to \code{FALSE}. If set to \code{TRUE}, prints out some details on the search request.
#' These include the full URL of the request, and some other information provided by the Table Builder.
#'
#' @details
#' If no responses are found for the query, a null object is returned.
#'
#' For \code{searchOption}, The default option is "all", which searches for the keywords in the both variables
#' and titles of tables. Other options are "variable", and "title", which searches for the keywords only in variables and titles
#' respectively.
#'
#' @return A data frame containing the search results. The first column is the resourceID for a SingStat table. The second column
#' is the table's corresponding title.
#'
#' @seealso \code{singstat_metadata}, \code{singstat_search}
#'
#' @examples
#' singstat_resource("employment")
#' singstat_resource("gdp", searchOption = "variable", printSummary = TRUE)
#' \dontrun{
#' singstat_resource("employment", searchOption = "none") #error}
#'
#'
#' @export


singstat_resource <- function(keyword, searchOption = "all", printSummary = FALSE) {
  if (stringr::str_detect(searchOption, stringr::regex("^all$|^variable$|^title$", ignore_case = TRUE))) {

    #Query construction
    queries <- list("keyword" = keyword,
                    "searchoption" = searchOption)

    #HTTP request
    request <- httr::GET(singstat_endpoint("resourceId"),
                         query = queries)

  } else {
      stop('Search Option provided is not a valid search option')
  }

  #Error checking for Get request
  httr::stop_for_status(request, task = "get a valid response from the server. Look up the HTTP error code in this message for more details")

  #Parse response object
  response <- jsonlite::fromJSON(httr::content(request, as = 'text'), simplifyDataFrame = TRUE)

  #More error checking just in case - it seems the API likes to return a 200 with its own error message in the response body
  if (!is.null(response$code)) {
    stop("The response from the server is good, but Singstat table builder has returned an error code. Details:",
         "\n",
         "Error Code: ",
         response$code,
         "\n",
         "Error Message: ",
         response$message
         )
  }


  #Return summary if requested
  if (printSummary == TRUE) {
    writeLines(c("URL:",
                 request$url,
                 "\n",
                 "Generated By:",
                 response$generatedBy,
                 "\n",
                 "Generated Date:",
                 response$generatedDate,
                 "\n",
                 "Number of Records:",
                 response$total))
  }

  response$Data$records

}
